### PR TITLE
Add --all option and some improvements

### PR DESCRIPTION
**Pull request by shadergz**

### CODE REVIEW

**Comment by xfgusta** [comment]
Hi. I changed a few things:

+ Removed some trailing whitespaces
+ Renamed Makefile to makefile
+ Removed `all` target from `.PHONY`
+ Added `install` and `uninstall` targets to `.PHONY`
+ Added the new option to the man page

I created co-authored commits to credit you.

Thanks for contributing!

**Comment by shadergz** [comment]
Don't mention it 😀! I appreciate your work and has glad for contribute to it

**Comment by xfgusta** [comment]
Please let me know if you're happy with these changes. Looks good to me. Can you test to see if it works?

You can clone the repo and apply the patch:
```text
git clone https://github.com/xfgusta/elfy
cd elfy
curl -O https://patch-diff.githubusercontent.com/raw/xfgusta/elfy/pull/1.patch
git apply 1.patch

**Comment by shadergz** [comment]
> Please let me know if you're happy with these changes. Looks good to me. Can you test to see if it works?

I has tested now, and works as expected! 😎

**Comment by xfgusta** [comment]
> > Please let me know if you're happy with these changes. Looks good to me. Can you test to see if it works?
> 
> I has tested now, and works as expected! sunglasses

Great! Thanks again.

**Pull request merged**
